### ISSUE TITLE
Mint a new release

### ISSUE THREAD

**Issue by shlomif** [thewml/website-meta-language#14]
I'd like to mint a new release tarball with the changes on the master branch. @xtaran : please let me know when the wml code is working for you so I can do it. Thanks!

**Comment by xtaran** [comment]
Looks fine.

I though wasn't able to create a release tar ball with cmake. There seems no such feature like `make dist` in cmake. I also found no equivalent for `make distclean`.

So I ended up doing `git clean -dxf; cd src/; tar cvJf ../../wml_2.10.2~rc1.orig.tar.xz ./ `, that gave me a tar ball with nearly the same file list as the previous one, only `cmake/Shlomif_Common.cmake` was missing. Copied that in manually from an older release.

With that tar ball as base for my Debian package, it works fine.

(Short rant: I really do not understand why people prefer cmake over autotools. It took me quite some time to get the Debian wml package working again after the IMHO unnecessary switch to cmake. Sorry, that had to be said once.)

**Comment by shlomif** [comment]
Hi @xtaran !

> Looks fine.
> 
> I though wasn't able to create a release tar ball with cmake. There seems no such feature like `make dist` in cmake. I also found no equivalent for `make distclean`.
> 

There is `make package_source` : https://cmake.org/cmake/help/latest/module/CPack.html .

> So I ended up doing `git clean -dxf; cd src/; tar cvJf ../../wml_2.10.2~rc1.orig.tar.xz ./ `, that gave me a tar ball with nearly the same file list as the previous one, only `cmake/Shlomif_Common.cmake` was missing. Copied that in manually from an older release.
> 
> With that tar ball as base for my Debian package, it works fine.
> 

OK.


> (Short rant: I really do not understand why people prefer cmake over autotools. It took me quite some time to get the Debian wml package working again after the IMHO unnecessary switch to cmake. Sorry, that had to be said once.)

I listed my reasons for preferring cmake here - https://www.shlomifish.org/open-source/anti/autohell/ . cmake does some tasks somewhat differently than autotools, but what you want to do is usually possible.

**Comment by shlomif** [comment]
I released 2.12.0. Closing this issue - thanks!

**Comment by xtaran** [comment]
Thanks for the two links!
