### ISSUE TITLE
The NAME entry in the POD of wml-params-conf misses the description

### ISSUE THREAD

**Issue by xtaran** [thewml/website-meta-language#16]
Debian's lintian emits the following warning:

W: wml: manpage-has-bad-whatis-entry usr/share/man/man1/wml-params-conf.1.gz

`src/wml_frontend/wml-params-conf.src` contains:

```
=head1 NAME

wml-params-conf
```

There is a short one-line description missing behind the program name (which needs to be separated by a dash), e.g.:

```
=head1 NAME

wml-params-conf - outputs the wml private library path 
```

P.S.: I intend to stop shipping `wml-params-conf` with the Debian wml package as it only seems to be needed during the build.

**Comment by shlomif** [comment]
> Debian's lintian emits the following warning:
> 
> W: wml: manpage-has-bad-whatis-entry usr/share/man/man1/wml-params-conf.1.gz
> 
> `src/wml_frontend/wml-params-conf.src` contains:
> 
> ```
> =head1 NAME
> 
> wml-params-conf
> ```
> 
> There is a short one-line description missing behind the program name (which needs to be separated by a dash), e.g.:
> 
> ```
> =head1 NAME
> 
> wml-params-conf - outputs the wml private library path 
> ```
> 

Should be fixed now.

> P.S.: I intend to stop shipping `wml-params-conf` with the Debian wml package as it only seems to be needed during the build.

Actually, it is meant for use by programs using the perl 5 API, e.g in https://github.com/shlomif/quad-pres/blob/master/installer/perl5/Shlomif/Quad/Pres/CmdLine.pm or https://github.com/shlomif/shlomi-fish-homepage/blob/master/bin/gen-helpers-main.pl . Not including it will break this code there, so please include it.

**Comment by xtaran** [comment]
> Not including it will break this code there, so please include it.

Thanks for the explanation. Will do!
