### ISSUE TITLE
Publish a new 2.30.0 version

### ISSUE THREAD

**Issue by shlomif** [thewml/website-meta-language#39]
@xtaran : hi! I wish to publish a new 2.30.0 version, with some cleanups and your "informations" pull-req applied. See:

* https://travis-ci.org/github/thewml/website-meta-language/builds/718866529

* https://github.com/thewml/website-meta-language/commit/45bd0d069e22686ceae6316000e145ad3cab5291

It would be great if you can review or test the changes. I'll release a new version once this ticket is closed.

Thanks!

**Comment by xtaran** [comment]
Thanks! I'll probably push some minor consistency fixups beforehand, like once `! p` and once `!p` (with and without the space inbetween) is used. Will also check if there are any patches in Debian left which should be upstreamed.

**Comment by xtaran** [comment]
I just pushed ebd7215b3ca54ff75434716649af9ebfc893a56d which uses `!p` consistently in at least this file (and consistently with all variables starting with a `p` :-), but at least under `src/wml_backend/p3_eperl/` there are more cases with blanks between exclamation mark and variable name. Not sure if it's worth the effort to streamline this, too.

**Comment by shlomif** [comment]
@xtaran : thanks for your work.

**Comment by xtaran** [comment]
Should be fine now, I think.

**Comment by shlomif** [comment]
@xtaran: 2.30.0 was packaged now - thanks! Closing this ticket.
