### ISSUE TITLE
Please disable tidyall.t for user installation

### ISSUE THREAD

**Issue by xtaran** [thewml/website-meta-language#4]
Depending on the exact version of Test::Code::TidyAll, the `tidyall.t` fails. E.g. with Code-TidyAll 0.67, the test suite fails as follows:

```
# [checked] wml_frontend/wmb.src
# *** needs tidying
#   Failed test 'wml_frontend/wmb.src is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Backends/ASubst/Main.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Backends/ASubst/Main.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Backends/Divert/Main.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Backends/Divert/Main.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Backends/HtmlStrip/Main.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Backends/HtmlStrip/Main.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Frontends/Wml/PassesManager.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Frontends/Wml/PassesManager.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Frontends/Wml/Runner.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Frontends/Wml/Runner.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Frontends/Wml/WmlRcDir.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Frontends/Wml/WmlRcDir.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Frontends/Wml/OptD.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Frontends/Wml/OptD.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# [checked] wml_include/TheWML/Frontends/Wml/Util.pm
# *** needs tidying
#   Failed test 'wml_include/TheWML/Frontends/Wml/Util.pm is tidy'
#   at t/tidyall.t line 4.
# *** needs tidying
# Looks like you failed 9 tests of 29.
t/tidyall.t .......... 
1..29
ok 1 - wml_frontend/wmu.src is tidy
ok 2 - wml_frontend/wmk.src is tidy
ok 3 - wml_frontend/wml.src is tidy
ok 4 - wml_frontend/wmd.src is tidy
not ok 5 - wml_frontend/wmb.src is tidy
ok 6 - wml_frontend/wmd_missing.src is tidy
ok 7 - wml_frontend/wml-params-conf.src is tidy
ok 8 - wml_backend/p1_ipp/ipp.src is tidy
ok 9 - wml_include/TheWML/CmdLine/Base.pm is tidy
ok 10 - wml_include/TheWML/CmdLine/IO.pm is tidy
not ok 11 - wml_include/TheWML/Backends/ASubst/Main.pm is tidy
not ok 12 - wml_include/TheWML/Backends/Divert/Main.pm is tidy
ok 13 - wml_include/TheWML/Backends/IPP/Line.pm is tidy
ok 14 - wml_include/TheWML/Backends/IPP/Main.pm is tidy
ok 15 - wml_include/TheWML/Backends/IPP/Delimit.pm is tidy
ok 16 - wml_include/TheWML/Backends/IPP/Map.pm is tidy
ok 17 - wml_include/TheWML/Backends/IPP/File.pm is tidy
ok 18 - wml_include/TheWML/Backends/IPP/Args.pm is tidy
not ok 19 - wml_include/TheWML/Backends/HtmlStrip/Main.pm is tidy
ok 20 - wml_include/TheWML/Backends/Fixup/Main.pm is tidy
not ok 21 - wml_include/TheWML/Frontends/Wml/PassesManager.pm is tidy
not ok 22 - wml_include/TheWML/Frontends/Wml/Runner.pm is tidy
not ok 23 - wml_include/TheWML/Frontends/Wml/WmlRcDir.pm is tidy
not ok 24 - wml_include/TheWML/Frontends/Wml/OptD.pm is tidy
not ok 25 - wml_include/TheWML/Frontends/Wml/Util.pm is tidy
ok 26 - wml_include/TheWML/Frontends/Wml/WmlRc.pm is tidy
ok 27 - wml_include/TheWML/Frontends/Wml/Protect.pm is tidy
ok 28 - wml_include/TheWML/Frontends/Wml/PassObj.pm is tidy
ok 29 - wml_include/TheWML/Config.pm.src is tidy
Dubious, test returned 9 (wstat 2304, 0x900)
Failed 9/29 subtests 

Test Summary Report
-------------------
t/tidyall.t        (Wstat: 2304 Tests: 29 Failed: 9)
  Failed tests:  5, 11-12, 19, 21-25
  Non-zero exit status: 9
Files=19, Tests=81, 27 wallclock secs ( 0.05 usr  0.04 sys + 24.77 cusr  1.82 csys = 26.68 CPU)
Result: FAIL
Running [prove -v t/02-p2_mp4h.t t/03-p3_eperl.t t/05-p5_divert.t t/06-p6_asubst.t t/07-p7_htmlfix.t t/08-p8_htmlstrip.t t/09-p9_slice.t t/10-wml.t t/des-gfont.t t/des-navbar.t t/des-space.t t/des-typography.t t/std-grid.t t/std-href.t t/std-lang.t t/std-tags.t t/std-toc.t t/build-process.t t/tidyall.t] failed! at /home/abe/wml/wml/wml_test/run_test.pl line 27.
```

There were other tests like

```
t/build-process.t .... skipped: Skipping because WML_TEST_BUILD is not set
```

which are not run upon user installation, so please do this for `tidyall.t` as well.

**Comment by shlomif** [comment]
On Sun, 16 Dec 2018 13:58:27 -0800
Axel Beckert <notifications@github.com> wrote:

> Depending on the exact version of Test::Code::TidyAll, the `tidyall.t` fails.
> E.g. with Code-TidyAll 0.67, the test suite fails as follows:
> 
> ```
> # [checked] wml_frontend/wmb.src
> # *** needs tidying
> #   Failed test 'wml_frontend/wmb.src is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Backends/ASubst/Main.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Backends/ASubst/Main.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Backends/Divert/Main.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Backends/Divert/Main.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Backends/HtmlStrip/Main.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Backends/HtmlStrip/Main.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Frontends/Wml/PassesManager.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Frontends/Wml/PassesManager.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Frontends/Wml/Runner.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Frontends/Wml/Runner.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Frontends/Wml/WmlRcDir.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Frontends/Wml/WmlRcDir.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Frontends/Wml/OptD.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Frontends/Wml/OptD.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # [checked] wml_include/TheWML/Frontends/Wml/Util.pm
> # *** needs tidying
> #   Failed test 'wml_include/TheWML/Frontends/Wml/Util.pm is tidy'
> #   at t/tidyall.t line 4.
> # *** needs tidying
> # Looks like you failed 9 tests of 29.
> t/tidyall.t .......... 
> 1..29
> ok 1 - wml_frontend/wmu.src is tidy
> ok 2 - wml_frontend/wmk.src is tidy
> ok 3 - wml_frontend/wml.src is tidy
> ok 4 - wml_frontend/wmd.src is tidy
> not ok 5 - wml_frontend/wmb.src is tidy
> ok 6 - wml_frontend/wmd_missing.src is tidy
> ok 7 - wml_frontend/wml-params-conf.src is tidy
> ok 8 - wml_backend/p1_ipp/ipp.src is tidy
> ok 9 - wml_include/TheWML/CmdLine/Base.pm is tidy
> ok 10 - wml_include/TheWML/CmdLine/IO.pm is tidy
> not ok 11 - wml_include/TheWML/Backends/ASubst/Main.pm is tidy
> not ok 12 - wml_include/TheWML/Backends/Divert/Main.pm is tidy
> ok 13 - wml_include/TheWML/Backends/IPP/Line.pm is tidy
> ok 14 - wml_include/TheWML/Backends/IPP/Main.pm is tidy
> ok 15 - wml_include/TheWML/Backends/IPP/Delimit.pm is tidy
> ok 16 - wml_include/TheWML/Backends/IPP/Map.pm is tidy
> ok 17 - wml_include/TheWML/Backends/IPP/File.pm is tidy
> ok 18 - wml_include/TheWML/Backends/IPP/Args.pm is tidy
> not ok 19 - wml_include/TheWML/Backends/HtmlStrip/Main.pm is tidy
> ok 20 - wml_include/TheWML/Backends/Fixup/Main.pm is tidy
> not ok 21 - wml_include/TheWML/Frontends/Wml/PassesManager.pm is tidy
> not ok 22 - wml_include/TheWML/Frontends/Wml/Runner.pm is tidy
> not ok 23 - wml_include/TheWML/Frontends/Wml/WmlRcDir.pm is tidy
> not ok 24 - wml_include/TheWML/Frontends/Wml/OptD.pm is tidy
> not ok 25 - wml_include/TheWML/Frontends/Wml/Util.pm is tidy
> ok 26 - wml_include/TheWML/Frontends/Wml/WmlRc.pm is tidy
> ok 27 - wml_include/TheWML/Frontends/Wml/Protect.pm is tidy
> ok 28 - wml_include/TheWML/Frontends/Wml/PassObj.pm is tidy
> ok 29 - wml_include/TheWML/Config.pm.src is tidy
> Dubious, test returned 9 (wstat 2304, 0x900)
> Failed 9/29 subtests 
> 
> Test Summary Report
> -------------------
> t/tidyall.t        (Wstat: 2304 Tests: 29 Failed: 9)
>   Failed tests:  5, 11-12, 19, 21-25
>   Non-zero exit status: 9
> Files=19, Tests=81, 27 wallclock secs ( 0.05 usr  0.04 sys + 24.77 cusr  1.82
> csys = 26.68 CPU) Result: FAIL
> Running [prove -v t/02-p2_mp4h.t t/03-p3_eperl.t t/05-p5_divert.t
> t/06-p6_asubst.t t/07-p7_htmlfix.t t/08-p8_htmlstrip.t t/09-p9_slice.t
> t/10-wml.t t/des-gfont.t t/des-navbar.t t/des-space.t t/des-typography.t
> t/std-grid.t t/std-href.t t/std-lang.t t/std-tags.t t/std-toc.t
> t/build-process.t t/tidyall.t] failed!
> at /home/abe/wml/wml/wml_test/run_test.pl line 27. ```
> 
> There were other tests like
> 
> ```
> t/build-process.t .... skipped: Skipping because WML_TEST_BUILD is not set
> ```
> 
> which are not run upon user installation, so please do this for `tidyall.t`
> as well.
> 

Thanks for the report! I'll work on it.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/open-source/resources/tech-tips/

average_drifter prefers something more lightweight than Windows Notepad. Like
Eclipse.
    — Freenode’s #perl-cats

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@xtaran : hi! It should be fixed now - can I close this?

**Comment by xtaran** [comment]
Yes, it's fixed. Thanks!
