### ISSUE TITLE
src/wml_frontend/wmd.txt and others might need a header update

### ISSUE THREAD

**Issue by xtaran** [thewml/website-meta-language#43]
Sorry for a bug report shortly after the release, but I became aware of this file's content via some new lintian tag (which has nothing to do with this issue, just made me look into that file):

`src/wml_frontend/wmd.txt` contains the following header:

```
Website META Language, Version 2.0.9 (18-Oct-2002)
Copyright (c) 1996-2001 Ralf S. Engelschall
Copyright (c) 1999-2001 Denis Barbier

Official homepage and distribution area:
http://www.engelschall.com/sw/wml/ <s>
 ftp://ftp.engelschall.com/sw/wml/ <s>

[…]
```

I think at least the URLs and maybe the version number and some dates should be updated.

URLs: Which one should be used? Probably these two:

* https://www.shlomifish.org/open-source/projects/website-meta-language/
* https://github.com/thewml/website-meta-language/

Version: Probably needs some rewriting on build time, hence non-trivial.

I grepped through the whole source code for the common part of the two old URLs and found it in these files:

```
→ git grep -Fl engelschall.com/sw/wml
docs/ANNOUNCE
src/wml_backend/p2_mp4h/doc/mp4h.mp4h
src/wml_contrib/tkwmd
src/wml_docs/wml_faq.pod
src/wml_docs/wml_macros.pod
src/wml_frontend/wmd.txt
src/wml_include/std/logo.src
src/wml_misc/logo-wml.info
```

Not urgent IMHO.

**Comment by shlomif** [comment]
@xtaran : please check if the recent commits fixed it.

**Comment by xtaran** [comment]
Yeah, I think 90d040731ace3aa00ed2617fd1deb497137f668a fixes the actual issue and the remaining ones look as if they could keep those things up to date wrt. version numbers.
