### ISSUE TITLE
wmu tries to connect to ancient www.engelschall.com website

### ISSUE THREAD

**Issue by xtaran** [thewml/website-meta-language#5]
Calling `wmu` results in the following error:

```
→ wmu
This is WML UPGRADE (WMu), Version 2.10.1
Copyright (c) 1996-2001 Ralf S. Engelschall.

1. Determine latest version:
   Website META Language, Version 
2. Determine distribution details:
Unable to get http://www.engelschall.com/sw/wml/distrib/<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Bad request!</title>
<link rev="made" href="mailto:rse@engelschall.com" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Bad request!</h1>
<p>


    Your browser (or proxy) sent a request that
    this server could not understand.

</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:rse@engelschall.com">webmaster</a>.

</p>

<h2>Error 400</h2>
<address>
  <a href="/">engelschall.com</a><br />
  
  <span>Tue Dec 25 07:41:41 2018<br />
  Apache/2.2.34 (OpenPKG/CURRENT)</span>
</address>
</body>
</html>
```

Probably should be changed to contact Github or the current homepage instead.

**Comment by shlomif** [comment]
On Mon, 24 Dec 2018 22:45:20 -0800
Axel Beckert <notifications@github.com> wrote:

> Calling `wmu` results in the following error:
> 
> ```
> → wmu
> This is WML UPGRADE (WMu), Version 2.10.1
> Copyright (c) 1996-2001 Ralf S. Engelschall.
> 

Thanks for the report - I'll investigate.

> 1. Determine latest version:
>    Website META Language, Version 
> 2. Determine distribution details:
> Unable to get http://www.engelschall.com/sw/wml/distrib/<?xml version="1.0"
> encoding="ISO-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0
> Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
> <head>
> <title>Bad request!</title>
> <link rev="made" href="mailto:rse@engelschall.com" />
> <style type="text/css"><![CDATA[/*></style>  
> </head>
> 
> <body>
> <h1>Bad request!</h1>
> <p>
> 
> 
>     Your browser (or proxy) sent a request that
>     this server could not understand.
> 
> </p>
> <p>
> If you think this is a server error, please contact
> the <a href="mailto:rse@engelschall.com">webmaster</a>.
> 
> </p>
> 
> <h2>Error 400</h2>
> <address>
>   <a href="/">engelschall.com</a><br />
>   
>   <span>Tue Dec 25 07:41:41 2018<br />
>   Apache/2.2.34 (OpenPKG/CURRENT)</span>
> </address>
> </body>
> </html>
> ```
> 
> Probably should be changed to contact Github or the current homepage instead.
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Freecell Solver - http://fc-solve.shlomifish.org/

Inigo Montoya: You seem a decent fellow. I hate to kill you.
The Man in Black: You seem a decent fellow. I hate to die.
    — http://en.wikiquote.org/wiki/The_Princess_Bride_%28film%29

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
I have deprecated wmu - thanks!

**Comment by xtaran** [comment]
> I have deprecated wmu - thanks!

You might want to also want to update the POD in `wmu.src`: https://github.com/thewml/website-meta-language/blob/master/src/wml_frontend/wmu.src#L51-L97

**Comment by shlomif** [comment]
On Tue, 25 Dec 2018 03:09:26 -0800
Axel Beckert <notifications@github.com> wrote:

> > I have deprecated wmu - thanks!  
> 
> You might want to also want to update the POD in `wmu.src`:
> https://github.com/thewml/website-meta-language/blob/master/src/wml_frontend/wmu.src#L51-L97
> 

Thanks! I'll do that.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Stop Using MSIE - http://www.shlomifish.org/no-ie/

 <rindolf>  RESOLVED / WONT_FIX / FUCK_YOU … story of my life.
    —  http://www.shlomifish.org/humour/fortunes/sharp-perl.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
