### ISSUE TITLE
Minor nitpick: https://github.com/thewml/website-meta-language points to non-HTTPS homepage which redirects to HTTPS

### ISSUE THREAD

**Issue by xtaran** [thewml/website-meta-language#6]
The link on top of https://github.com/thewml/website-meta-language points to the non-HTTPS homepage http://www.shlomifish.org/open-source/projects/website-meta-language/ which then redirects to HTTPS link at https://www.shlomifish.org/open-source/projects/website-meta-language/. Should be the HTTPS variant already on GitHub.

**Comment by shlomif** [comment]
Fixed, thanks!
