### ISSUE TITLE
http://thewml.org/ gives "connection refused"

### ISSUE THREAD

**Issue by xtaran** [thewml/website-meta-language#7]
https://www.shlomifish.org/open-source/projects/website-meta-language/ has a link to http://thewml.org/, but that host doesn't seem to listen on port 80. At least my browser tells me "connection refused". (Port 443 for HTTPS doesn't seem to be open on thewml.org either.)

**Comment by shlomif** [comment]
Fixed, thanks! Also see https://www.shlomifish.org/meta/FAQ/#broken_links .

**Comment by xtaran** [comment]
> Fixed, thanks!

Ah, by deleting it. That's unexpected.

> Also see https://www.shlomifish.org/meta/FAQ/#broken_links .

Sure, but I thought that thewml.org is under your control and the issue is a not-running or crashed webserver, not a broken third-party website. Guess I was wrong, thewml.org has engelschall.com DNS servers and hence indeed looks like legacy stuff...

**Comment by shlomif** [comment]
> > Fixed, thanks!
> 
> Ah, by deleting it. That's unexpected.

I did not delete it - I just moved it to the bottom of the ul element, and added a link to archive.org.
> 
> > Also see https://www.shlomifish.org/meta/FAQ/#broken_links .
> 
> Sure, but I thought that thewml.org is under your control and the issue is a not-running or crashed webserver, not a broken third-party website. Guess I was wrong, thewml.org has engelschall.com DNS servers and hence indeed looks like legacy stuff...
